# Generated by Django 5.0.1 on 2024-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_bid_start_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
